### ISSUE TITLE
Pounder attenuators are interfaced directly to Stabilizer SPI

### ISSUE THREAD

**Issue by ryan-summers** [quartiq/stabilizer#103]
The Pounder attenuators are powered by 5V rails and are directly connected to the STM32 SPI interface, which is powered by 3.3V rails. The voltage levels appear to work properly and communication completes successfully, but we should investigate using level shifting here.

**Comment by dtcallcock** [comment]
Please cross-post hardware issues with the sinara-hw repository if possible so we have everything in one place when it comes to new revisions.
