### ISSUE TITLE
Eth PHY reset time might not be long enough

### ISSUE THREAD

**Issue by HarryMakes** [quartiq/stabilizer#141]
When powering the board with 12V, the Ethernet PHY LAN8742A won't have enough time to reset sometimes. If the reset is done and long enough, the two LEDs on the RJ45 plug should blink briefly upon power-cycling the board - this can't be observed when the PHY hasn't been reset properly.

A solution is to lengthen the deassertion of the nRST signal to **25ms** by replacing [this line](https://github.com/quartiq/stabilizer/blob/master/src/main.rs#L551) in src/main.rs. According to the [PHY's datasheet](http://ww1.microchip.com/downloads/en/DeviceDoc/DS_LAN8742_00001989A.pdf), this should be sufficient for the duration of "external power supplies at operational level to nRST deassertion".

**Comment by jordens** [comment]
t_RSTIA is 100 µs.

![image](https://user-images.githubusercontent.com/1338946/95864640-f482c180-0d65-11eb-971c-944563298494.png)

But arguably there should be sufficient delay between power supply ramp up and that reset. The setup before that may not take long enough.

**Comment by jordens** [comment]
Changing it in software doesn't appear to alter behavior. Changing it in hardware is sinara-hw/Stabilizer#84
