### ISSUE TITLE
Measurements: Bode plot

### ISSUE THREAD

**Issue by nkuh** [quartiq/stabilizer#148]
# Bode plots of Stabilizer's transfer function

Default setup:
- Network Analyzer: Omicron Bode 100
- Stabilizer HW v1.1
- Stabilizer Ch0
- ADC0 50 Ohm term.

![index](https://user-images.githubusercontent.com/65332050/95569885-7a310500-0a26-11eb-8164-6272b3da4cbd.jpg)

**Comment by nkuh** [comment]
![(kp;ki;g)=(1;0;10)](https://user-images.githubusercontent.com/65332050/95568977-35589e80-0a25-11eb-96fb-bdbd760c73e9.PNG)

**Comment by nkuh** [comment]
![(kp;ki;g)=(1;0 1;10)](https://user-images.githubusercontent.com/65332050/95569041-4dc8b900-0a25-11eb-8c74-1afaed909927.PNG)
(kp;ki;g)=(1;0 1;10)

**Comment by nkuh** [comment]
![PD(k;g;f0)=(1;1000;5kHz)](https://user-images.githubusercontent.com/65332050/95584847-a193cc00-0a3e-11eb-8c0c-a81953b624e4.PNG)
PD(k;g;f0)=(1;1000;5kHz)

**Comment by nkuh** [comment]
![PD(k;g;f0)=(1;1000;5kHz)+LP(k;f0)=(10;100Hz)](https://user-images.githubusercontent.com/65332050/95723083-09335c80-0c75-11eb-8e18-700eaa15674b.PNG)
2 additive Biquads: PD(k;g;f0)=(1;1000;5kHz)+LP(k;f0)=(10;100Hz)

**Comment by jordens** [comment]
Nice data. Let's close it since there is no issue to be resolved. If more docs/characterization arises, this should be integrated.
