### ISSUE TITLE
SPI ADC sampling does not follow SPI ADC setup time

### ISSUE THREAD

**Issue by ryan-summers** [quartiq/stabilizer#219]
Although programming intentionally specifies a 220ns setup period for the SPI ADCs, it appears that is not currently being respected. This results in essentially a 1-cycle latency in the ADC code readout, as the SCK clocks out the _previous_ ADC sample.

**Comment by ryan-summers** [comment]
This appears to occur because the SPI DMA was configured to trigger sampling via the TXFIFO write as opposed to setting CSTART in the SPI config register. Because of this, I believe the configured MSSI/MIDI values of the SPI peripheral are not operating as intended.

**Comment by jordens** [comment]
Argh. I remember that was actually the reason I was triggering via CSTART instead of (re-)triggering via TX data.

**Comment by ryan-summers** [comment]
The workaround isn't super painful honestly - it's just a tad janky. I'll get a PR setup to fix it.

**Comment by jordens** [comment]
It's just re-introducing the old CSTART static as DMA data, right?

**Comment by ryan-summers** [comment]
Correct

**Comment by ryan-summers** [comment]
After further investigation, it doesn't appear that the old CSTART static -> CR1 fix can be applied now given that we use DMA to collect multiple samples in a batch.

When using the above methodology, we have to clear the transfer-complete interrupt flag before starting the next transfer, or it will be silently discarded.

Possible solutions:
* Drive CSn + SPI transfer timing via a hardware timer
* Investigate using MIDI to automatically handle this properly? Resolution may not be good enough
* DMA transfer can be configured to automatically clear the TCIF between ADC samples
