### ISSUE TITLE
Read MAC address from EEPROM

### ISSUE THREAD

**Issue by cjbe** [quartiq/stabilizer#23]
The MAC address should be read from the EEPROM, which has built in EUI48.

I need this and am happy to implement it.
My initial plan would be to print the MAC address found on startup via semihosting - this requires the user have an STLink. Another option would be to dump the MAC address over the debug UART, which comes out to a header. 

@jordens any preferences on how to get the MAC address out?

**Comment by jordens** [comment]
I'd stick to the procedure in the ARTIQ runtime for Kasli as much as possible.

**Comment by dnadlinger** [comment]
It's easy enough to figure out the MAC address using Wireshark if the device generates some network traffic (e.g. DHCP). Still not exactly end-user-friendly, but at least doesn't necessitate playing around with debug cables.

For actual units sold, surely board houses selling Stabilizer will have some infrastructure to read the EUI-48 and print a per-unit sticker? This must be a reasonably common requirement in manufacturing digital things.

**Comment by hartytp** [comment]
> For actual units sold, surely board houses selling Stabilizer will have some infrastructure to read the EUI-48 and print a per-unit sticker? This must be a reasonably common requirement in manufacturing digital things.

This is something I wish our suppliers did.

**Comment by cjbe** [comment]
@dnadlinger agreed re finding MAC address - my worry is more the debugging associated with getting the board up (e.g. is the system trying to get a DHCP lease, was it successful and the problem is now elsewhere...) in a way that it is easy to instruct someone to do.

Connecting a debug cable / a USB-UART cable is on the edge of easy enough to get someone to do...

**Comment by jordens** [comment]
FYI: QUARTIQ now does MAC stickers and tracks devices sold.
