### ISSUE TITLE
I2C EUI-48 readout unreliable

### ISSUE THREAD

**Issue by dnadlinger** [quartiq/stabilizer#294]
From time to time, the EUI-48 readout (MAC address) from the I2C EEPROM chip appears to be unreliable.

I've now observed this two times, on two different boards. Each time, the v1.1 Stabilizer in question was sitting happily in a corner somewhere with JTAG and power connected constantly, being reprogrammed as I was working on the firmware. The first time, the I2C transactions started failing altogether at some point. The second time, the address read back was 80:00:10:4d:03:8b consistently instead of the usual (presumably correct) 80:1f:12:5d:47:df. Both times, the behaviour was consistent across JTAG resets (`monitor reset halt`) and full reloads. Completely power-cycling the board (removing both 12 V in and the JTAG programmer) fixed the issue.

Any idea what could be going on here? This is quite possibly a hw issue; I'll try putting a scope on the bus next time.

**Comment by dnadlinger** [comment]
The I2C bus is set to 100 kHz - should be fine, as we are powering the EEPROM from 3V3, where its specified max. clock frequency is 400 kHz.

**Comment by jordens** [comment]
My guess is the mosfets or their drive (through the AFE supply?)

**Comment by dnadlinger** [comment]
With a Stabilizer v1.1 hooked up to a AKM65US12 12 V supply and a ST-Link v2 connected, the EEPROM read fails consistently, in a fashion detected by the core, after powerup. With the PSU connected to a network-controlled power switch, I didn't observe a single success in some dozen attempts.

For those boots, a manual `monitor reset` some seconds later always resulted in a correct readback whenever I tried (sample size: ~5).

Bodging in 1e7 DSBs at the beginning of `hardware::init` for a second or two of delay seems to avoid this problem. (This doesn't necessarily seem to be the same issue I observed previously, where I got wrong readback when running within the debugger.)

**Comment by dnadlinger** [comment]
Okay, this makes sense. T1/T3 only connect the I2C bus once P12V0A is up (as a proxy for the power sequence being complete), but that rail takes a few seconds to come up, as it's generated by a LT3042 without fast start.

**Comment by dnadlinger** [comment]
Just waiting until the read doesn't work; I consistently get d8-80-39-ef-13-ab instead of  80-00-10-4d-03-8b after power-up this way.

**Comment by dnadlinger** [comment]
Just reading again after the first "successful" read seems to work for me (sample size: 10), but some more robustness testing is probably in order.

**Comment by ryan-summers** [comment]
Just an FYI that it's possible that v1.1 statiblizer P12V0A _never_ comes up and the device requires a reboot to succeed. This is a known fault in V1.1 hardware. https://github.com/sinara-hw/Stabilizer/issues/87 is the reference of my observations.

**Comment by jordens** [comment]
Let's:

* Read until ACK or 10s timeout.
* Panic if timeout
* Read once again
* No default MAC address

**Comment by dnadlinger** [comment]
I've also seen an issue where plugging a bare ribbon cable (without anything at the remote end) repeatedly  caused the I2C read to fail (Extra capacitive load? I didn't try a second cable, but the chance of a short/... is extremely low.). Perhaps it's worth reducing the clock frequency a bit?

**Comment by ryan-summers** [comment]
I agree with Robert here. Without traces + analysis and such showing that the I2C bus frequency is too high, I don't think that's a viable solution to this issue. We already know one likely hardware fault at work here, so let's not confound multiple things at once.

**Comment by jordens** [comment]
@dnadlinger which I2C read fails in that case? The ["second one"](https://github.com/quartiq/stabilizer/issues/294#issuecomment-792351078) or all of them? My guess is that the mosfets are not yet conductive enough during the slow ramp up making the bus marginal.

**Comment by jordens** [comment]
I also think the power sequence annotation is wrong. CPU_RESETn is release before the N/P12V0A supplies.

![image](https://user-images.githubusercontent.com/1338946/113018888-48049280-9181-11eb-8c1f-b63414dcf9a5.png)

**Comment by dnadlinger** [comment]
While the weird behaviour with the EEM cable was perfectly reproducible over a few tries, the piece of hardware this was on is now in active duty, and I wasn't successful in reproducing this on a different unit. As Robert points out, the necessary capacitance/… doesn't appear to add up with sensible drive strength, so I'm not sure what's going on there – something related to the bus switch turn-on might explain it. As much as I'd like to track this down properly, I don't have the hardware (and bandwidth) to build a second copy of the system now on laser lock duty, so let's ignore this for now until we have a solid test case.

To avoid any issues with half-conducting FETs, we should probably wait until a read "succeeds", delay for, say, 100 ms, and only then actually read the MAC address.
