### ISSUE TITLE
build broken (smoltcp repo)

### ISSUE THREAD

**Issue by jordens** [quartiq/stabilizer#316]
https://github.com/quartiq/stabilizer/runs/2190414995?check_suite_focus=true

fixed by #314

**Comment by ryan-summers** [comment]
Yeah. I had noticed this yesterday. The problem arises if we're depending on remote branches. If those branches get merged and removed, the build breaks here.

I would recommend that going forward, we try to merge dependencies first - this is a process I've intended, to follow, but haven't always followed through on. I'll keep this in mind moving forward and PR a dependency fix for this.

**Comment by jordens** [comment]
Ack.
Sidenote: I can't seem to get `cargo update` to cleanly update individual git dependencies without causing unintended and broken updates elsewhere. This is especially noticeable in `fls`. I suspect the hash (not the branch + hash in `Cargo.lock`) should be used in `Cargo.toml`.
