### ISSUE TITLE
streaming: better buffering

### ISSUE THREAD

**Issue by jordens** [quartiq/stabilizer#385]
Reduce the number of copies for streaming:

* The high prio process task should directly serialize into a fixed-size buffer A (about 1 kB).
* If A is full and another buffer A' (that's been released from the low prio network stack task) is available it designates A as B and switches over to filling A' (format ID and start batch number and first batch)
* If there is no A' available it drops the batch.
* If the network stack low prio task has a full buffer B available it copies it into the smoltcp socket buffer and designates the now free buffer B as A' closing the loop.
* Maybe this entire thing is easiest with a heapless `Pool` for the three buffers and heapless boxes for the full ones into a N=4 spsc queue (https://github.com/japaric/heapless/issues/210) to implement the concurrency (like [here](https://github.com/stm32-rs/stm32l4xx-hal/blob/master/examples/rtic_frame_serial_dma.rs)).
* Once https://github.com/smoltcp-rs/smoltcp/issues/422 is fixed these three buffers would all be smoltcp UDP packet buffers and the network task would only enqueue.

At the same time we should do the following:

* Make the streaming generic over the batch data format, or better generic over the size of the u8 slice to serialize each batch data into. Applications will want to not only log 2ADC and 2 DAC but other things instead or additionally.
* The frame header hould be `#[repr(C)] {sequence: u16, format: u16}` where `sequence` is the sequence number of the frame (not the first batch in the frame: frame size is fixed and batch format/size is defined elsewhere), format is an opaque format ID defined by the application defining the contents of a batch. `format` implies batch data size. Frame size minus header size implies number of batches contained.
* Endianess should be device-endian for everything.
* Rewrite streaming docs afterwards

**Comment by ryan-summers** [comment]
> The high prio process task should directly serialize into a fixed-size buffer A (about 1 kB).

I do not know if we actually want to do this. The serialization process can sometimes be relatively high on overhead (depending on serialization implementation).If the serialization is a memcpy, then I would recommend we still just copy the raw object into the pool and then do the "serialization" in the low priority task. We could likely just transmute the object into a raw buffer for transmission in the trivial memcpy case.

**Comment by jordens** [comment]
Yes. "Serialization" is the wrong term here. It's just copying. The pool would be of frames, not of batches. The low prio task only fills in the header (if that's where it ends up) and hands the frame to smoltcp.

**Comment by ryan-summers** [comment]
What benefit do we get of having a frame of many batches (e.g. spsc of [Box; N]` over an spsc::Queue of `Box`?

It seems to me like that just adds the complexity of figuring out where to enqueue a new Box into the dsp process. Why not just fill up a single `Box` per batch and let the lower priority figure things out?

**Comment by jordens** [comment]
What I described above is a `Queue` of `Box`es of frames. As described it's advantageous to fix the frame size and do so early (before the queue). And it's advantageous to make the chunk passed into smoltcp as large as possible (not individual batches).
The Frame is just the header plus a `[[u8; BATCH_SIZE]; BATCHES_PER_FRAME]`, there is little complexity to figure out where to put a batch.

**Comment by ryan-summers** [comment]
But there's still the problem of where to actually perform the serialization of the data generated in the DSP process into a `[u8]` slice. Because we have said that process should occur in the low priority task, it makes no sense to me why we would have an entire Frame get filled in the high priority task. We still need to then sequentially go through each item in the frame and serialize it at the lower priority into the buffer for transmission.

Are you actually implying that the high priority task should also be responsible for serialization into the final format that will be sent on the wire?

**Comment by jordens** [comment]
That "serialization" from whatever the application wants to stream into u8 should be done in the high prio task. I don't think there is much to it. Certainly not overhead beyond memcpy.
Or do you see an issue with that?

**Comment by ryan-summers** [comment]
Memcpy is super problematic from a rust structure. If we don't use a `repr(packed)` format for the data, we will have a ton of padding/alignment bytes in the final format. However, [`repr(packed)` can still result in undefined behavior](https://doc.rust-lang.org/nomicon/other-reprs.html#reprpacked).

Thus, I imagine the serialization process will be more comprehensive than a simple memcpy - we would have to place the data manually

**Comment by jordens** [comment]
I don't see how there will be padding. But sure. Use `repr(C, packed)`. In any case, this is a choice at the application level.

**Comment by jordens** [comment]
I suppose we could actually use MDMA to do shuttle the ADC and DAC data automatically from axisram to the frame buffer (and after two layers of smoltcp improvements even directly into the ETH DMA buffer). Then apart from framing and management there is zero overhead.
