### ISSUE TITLE
HITL for streaming

### ISSUE THREAD

**Issue by jordens** [quartiq/stabilizer#386]
* Set up stream
* Parse a few incoming frames and verify that format and batch ID makes sense
* Disable stream

**Comment by ryan-summers** [comment]
I would like to expand this to include modifying the IIR filters to output static values and then confirm that the ADCs/ADCs are reading/writing this value. That would then help us validate the hardware portions of the system as well, which is a lot of value added.

**Comment by jordens** [comment]
I would do that check through the telemetry (thereby testing telemetry as well).
And then test streaming data against telemetry data.
That avoids depending on streaming to test for basic ADC/DAC functionality (and only uses settings/telemetry/MQTT).
