### ISSUE TITLE
Relicense as MIT/Apache

### ISSUE THREAD

**Issue by jordens** [quartiq/stabilizer#413]
I want to relicense the code in this repository from GPLv3 to [MIT](https://choosealicense.com/licenses/mit/)/[Apache](https://choosealicense.com/licenses/apache-2.0/).

* The DSP crate, AD9959 etc should ultimately be factored out of this repo. They are stand-alone code that is extremely useful in other applications.
* We are already seeing that things are being "reimplemented" under different licenses based on the code here. This is unfortunate, against the copyright terms yet I would like to see exactly that widespread code uptake. Under GPL or LGPL we don't expect significant synergies while under MIT/Apache we do.
* Stabilizer is becoming more of a library of well-defined standard algorithms. The actual IP one would want to protect lies in the use of those algorithms and their composition into new schemes. GPL doesn't allow us to easily build non-GPL software (like fls) from the library code here.

If your agreement on this isn't already implied by contract, please comment below and indicate your support/opposition. Note that to enable the relicensing the contributions of those who disagree will be removed.
Deadline is 2021-07-28 09:00:00 UTC.

[Contributors](https://github.com/quartiq/stabilizer/graphs/contributors):

* [x] @jordens [commits](https://github.com/quartiq/stabilizer/commits?author=jordens)
* [x] @ryan-summers [commits](https://github.com/quartiq/stabilizer/commits?author=ryan-summers)
* [x] @matthuszagh [commits](https://github.com/quartiq/stabilizer/commits?author=matthuszagh)
* [x] @SingularitySurfer [commits](https://github.com/quartiq/stabilizer/commits?author=SingularitySurfer)
* [x] @cjbe [commits](https://github.com/quartiq/stabilizer/commits?author=cjbe)
* [x] @HarryMakes [commits](https://github.com/quartiq/stabilizer/commits?author=HarryMakes)
* [x] @sbourdeauducq [commits](https://github.com/quartiq/stabilizer/commits?author=sbourdeauducq)
* [x] @dnadlinger [commits](https://github.com/quartiq/stabilizer/commits?author=dnadlinger)
* [x] @sergachev [commits](https://github.com/quartiq/stabilizer/commits?author=sergachev)
* [x] @nkuh [commits](https://github.com/quartiq/stabilizer/commits?author=nkuh)

**Comment by ryan-summers** [comment]
I did a quick audit of the dependencies of `stabilizer as well:
```
$ cargo license
0BSD (3): managed, smoltcp, stm32h7xx-hal
Apache-2.0 (1): rtt-logger
Apache-2.0 OR BSL-1.0 (1): ryu
Apache-2.0 OR MIT (70): aligned, as-slice, autocfg, bare-metal, bare-metal, bit_field, bitfield, bitflags, cast, cfg-if, cortex-m, cortex-m, cortex-m-rt, cortex-m-rt-macros, cortex-m-rtic, cortex-m-rtic-macros, derivative, easybench, embedded-dma, embedded-hal, embedded-nal, getrandom, hash32, hash32, hashbrown, heapless, heapless, indexmap, log, matrixmultiply, mutex-trait, nb, nb, ndarray, num-complex, num-integer, num-traits, paste, pest, ppv-lite86, proc-macro2, quote, rand, rand_chacha, rand_core, rawpointer, rtic-core, rtic-syntax, rustc_version, rustc_version, semver, semver, semver-parser, semver-parser, serde, serde-json-core, serde_derive, shared-bus, smlang, smlang-macros, stable_deref_trait, stm32h7, syn, typenum, ucd-trie, ufmt-write, unicode-xid, vcell, version_check, volatile-register
BSD-3-Clause (2): num_enum, num_enum_derive
GPL-3.0-or-later (1): stabilizer
MIT (13): asm-delay, bitrate, enum-iterator, enum-iterator-derive, generic-array, generic-array, generic-array, mcp23017, minimq, no-std-net, rtt-target, smoltcp-nal, void
MIT OR Unlicense (1): byteorder
N/A (4): ad9959, derive_miniconf, dsp, miniconf
Zlib (1): nanorand
```

I don't see anything here that would be in conflict with an MIT/Apache license.

**Comment by jordens** [comment]
https://github.com/quartiq/miniconf/issues/23 for the miniconf license.

**Comment by sbourdeauducq** [comment]
I disagree with the general strategy, but I don't care enough about GPLv3 vs MIT/Apache in this case to block relicensing of my/M-Labs' contributions.

**Comment by dnadlinger** [comment]
> We are already seeing that things are being "reimplemented" under different licenses based on the code here. This is unfortunate, against the copyright terms yet I would like to see exactly that widespread code uptake.

Imho GPLv3 works exactly as intended here: The virality neatly terminates at the network boundary anyway (so e.g. a fancy proprietary system identification UI wouldn't be affected), while requiring the "boring" hardware bits to be shared. I don't really see how any nebulous synergies would benefit a typical physicist user, given that the biggest challenge is actually sorting out all the boring details necessary for robust operation (the upstream version is only now slowly getting usable in that regard!), not writing a IIR filter implementation of acceptable quality.

Which are those "reimplementations", by the way?

I don't agree with a license change, but I doubt my changes in the upstream repo would be copyrightable anyway. (This is not to say I'd categorically exclude contributing to a Apache/MIT-licensed version in the future.)

**Comment by jordens** [comment]
Network applications are irrelevant here. This is about firmware applications. I also don't expect any direct physicist benefits: this is predominantly a software development and business strategy.
The synergies may well be nebulous to you, but I unfortunately don't have the bandwidth to explain this.

@dnadlinger please make this easy and explicit by saying that you don't consider your contributions copyrightable.
@sbourdeauducq could you please explicitly say, that you are OK (or not) with relicensing (or that you don't consider your contributions copyrightable)? Saying that you "don't care enough .. to block relicensing" may satisfy your need to express whatever frustration you feel but it is too indirect to answer the question.

**Comment by dnadlinger** [comment]
While significant debugging effort went into my couple of upstream contributions, I don't consider the actual changes copyrightable – for simplicity and to avoid messy differences in copyright across jurisdictions, feel free to just relicense them as Apache/MIT.

I certainly don't want to make your life unnecessary hard regarding what is pretty clearly "your" codebase just because you happened to merge one of my PRs in the past, and as a user, there being more reasons for QUARTIQ to maintain this repo can only be a good thing. If you ever have time to spare, or next we meet a conference (once those are a thing again), I'd be quite curious as to the reasoning, though, as what I would consider a "good" development model for ARTIQ-adjacient products would definitely be GPL-compatible.

**Comment by sbourdeauducq** [comment]
I am OK with the relicensing of my contributions.

**Comment by jordens** [comment]
No need to imagine things. Closed source ARTIQ-adjacent products are discussed in the ARTIQ relicensing issue, delineated in detail in the ARTIQ README, and they are precisely the reason why ARTIQ is not GPL. I don't expect Riverlane, AQT, or Oxford Ionics etc products using ARTIQ to be released under GPL.
The level of "ARTIQ-adjacency" of the stabilizer firmware is completely insignificant.

**Comment by sergachev** [comment]
My contribution is tiny. I am fine with relicensing.

**Comment by matthuszagh** [comment]
I'm ok with the relicensing of my contributions.

**Comment by nkuh** [comment]
I'm ok with the relicensing of my contributions.
