### ISSUE TITLE
dependency clean up

### ISSUE THREAD

**Issue by jordens** [quartiq/stabilizer#454]
Let's review the publication blocker dependencies before 0.6

https://github.com/quartiq/stabilizer/blob/015b719322fe74c421c4d0d42977f024f675c5a4/Cargo.toml#L53-L83

* [x] rtt-logger: fork or in-line. It's small
* [x] hal: bump to 0.10. Or is smoltcp blocking?
* [x] cortex-m-rt: depends on newer hal using c-m
* [x] heapless: assume-init wont be merged
* [x] smoltcp-nal: synchronize with hal's dependency on smoltcp, then release
* [x] miniconf: release

**Comment by jordens** [comment]
@ryan-summers all but `heapless` done. I wonder whether we are really using that `MaybeUninit` stuff correctly (context for our fork was https://github.com/japaric/heapless/issues/222).

**Comment by ryan-summers** [comment]
This has been on the backburner of my brain for a while now, I just haven't had time to look more into it. Would be happy to if we want to close this out
