### ISSUE TITLE
AsmDelay delays are likely 1/4th the time they should be.

### ISSUE THREAD

**Issue by nkrackow** [quartiq/stabilizer#524]
https://github.com/quartiq/stabilizer/blob/96732cbea115efaa2012b69fc23fa18f95a56298/src/hardware/setup.rs#L277-L279

As discovered here https://github.com/quartiq/thermostat-eem/issues/27, the delays are not the expected time on the STM32H7. Since Stabilizer has the same CPU it should be affected too.

**Comment by ryan-summers** [comment]
I measured a GPIO assertion using a 200uS delay to control the pulse size and observed that the pulse was actually 50uS on an oscilloscope, which indicates this affects us as well.
