### ISSUE TITLE
May I ask some questions？

### ISSUE THREAD

**Issue by Jzow** [quartiq/stabilizer#544]
I want to add automated **robots** and **bors** to my warehouse. At first, the **bors** I configured was successful in the root directory when I moved it to In the **.gitHub/workflow** directory, he has a problem that he can't find. I'm sorry if I disturb you

**Comment by jordens** [comment]
What's the question? Probably best to check your spelling and ask it over atthe bors repo.

**Comment by Jzow** [comment]
ok, thanks 


> 在 2022年5月24日，02:10，Robert Jördens ***@***.***> 写道：
> 
> What's the question? Probably best to check your spelling and ask it over atthe bors repo.
>
