### ISSUE TITLE
temperature sensor support (cpu on stabilizer and lm75 on pounder)

### ISSUE THREAD

**Issue by jordens** [quartiq/stabilizer#568]
* The CPU has an internal temperature sensor connected to ADC3. Implement that and add it to telemetry in `dual-iir`/`lockin`.
* Pounder has an LM75 connected via I2C. Implement that and add it to the Pounder API (to be added to application telemetry)

**Comment by nkrackow** [comment]
I've already added the LM75 for Driver here: https://github.com/quartiq/stabilizer/blob/302295e2ae97a7489bee1193e10158c08d8f4479/src/hardware/setup.rs#L986
but I haven't tested it as I don't have HW.. But perfect, then I can just use Pounder for testing here.
I'm not sure if there is much custom code that we can re-use between Driver and Pounder, it's just instantiating the LM75 so far.
The crate looks nice at least.
