### ISSUE TITLE
`y_min` value trumps `y_max`

### ISSUE THREAD

**Issue by nkrackow** [quartiq/stabilizer#628]
When you set the `y_min` value of the IIR to a point higher than `y_max`, the output will take the `y_min` value. I'm not sure if this is a problem, just wanted to note this for now.
Observed using Driver but should be the same for Stabilizer.

**Comment by jordens** [comment]
Originates at https://docs.rs/num-traits/0.2.14/src/num_traits/lib.rs.html#387-396 
Other than validating `y_min <= y_max` on the host or on the device there is nothing that can be done. It'll panic in debug mode though.

**Comment by nkrackow** [comment]
Not an issue then.
