### ISSUE TITLE
stabilizer v1.1 hardware support

### ISSUE THREAD

**Issue by jordens** [quartiq/stabilizer#66]
@gkasprow needs it to do basic testing on the v1.1 batch

[Change list](https://github.com/sinara-hw/Stabilizer/issues/32
): Only SPI shuffling?

**Comment by jordens** [comment]
@hartytp @cjbe @dtcallcock What's the plan with supporting Stabilizer v1.1 (potentially in parallel with v1.0)? Are you going to port that and maintain it?

**Comment by hartytp** [comment]
>ADC SPI buffers replaced by SN74AUC2G34DCKR 

I assume that will also allow us to push the sample rate up a little?

I'm not aware of us having much of a plan for this, other than we'll sort something out when we need it.

**Comment by jordens** [comment]
I had the impression from the push for v1.1 that you had a plan for and you need it.

**Comment by hartytp** [comment]
Yes, we need some more boards somewhat soon and I wanted to get the dumb stuff like oscillating references/missing traces fixed first.

**Comment by jordens** [comment]
The way I see it, if anyone wants these boards anytime soon, then this port needs to happen now, at least to some extent.

**Comment by dtcallcock** [comment]
How does this relate to the shielding can?

For the port, if it’s just moving a few SPI lines, can you do us a solid and fix it next time you’re making changes to the code?

**Comment by jordens** [comment]
Exactly as much as your question which the comment is a reply to.

**Comment by dtcallcock** [comment]
Ah, I see the shielding can thread was where Greg asked how many units we need.

Anyway, are you saying that to support v1.1 hardware you need an extra contract working up and paying for?  This definitely isn't a small enough job that you can't just cover it by rounding up on some future contract or pay for it with the proposed hardware sales tax?

**Comment by jordens** [comment]
Turns out that we can use pounder+stabilizer in a different project next nicely. We'll do a basic port and trial the scatter-gather approach to get the ROI.

**Comment by jordens** [comment]
https://github.com/quartiq/stabilizer/commit/2ddcdec537922c349226fb07d6d3f976aa47d63e
