### ISSUE TITLE
Lock `miniconf-mqtt` python utilities to a tag

### ISSUE THREAD

**Issue by ryan-summers** [quartiq/stabilizer#661]
Given that `miniconf` is undergoing heavy changes and development right now, the current `main` branch is incompatible with released `miniconf` versions. We should use a tag reference for the Python client similar to `cargo.toml`

**Comment by jordens** [comment]
Let's just release the miniconf client to pypi properly and install a specific version from there.

**Comment by jordens** [comment]
Done here in https://github.com/quartiq/stabilizer/commit/fdaa6d46ef7469b2081a4cfa461a57fc965218c7 but should just be a miniconf pypi release.

**Comment by jordens** [comment]
Agreed. Explicit dependency is fine.
