### ISSUE TITLE
use dhcp default gateway as default broker

### ISSUE THREAD

**Issue by jordens** [quartiq/stabilizer#672]
Instead of hardcoding a broker, we could (before switching to DNS-SD/mDNS) just use the default gateway as the default broker (unless overridden in compile time environment variables).

Dunno how easy it is to fish for the DHCP default gateway in the smoltcp stack.

* it's a reasonable default, installing and running the broker on the default gateway is often easy and convenient. If not portforwarding could do the rest.
* would avoid #518 in some cases
* #351 for other ways to configure the broker

**Comment by ryan-summers** [comment]
Closing as no longer necessary. The broker is now specified via DNS
