### ISSUE TITLE
stream to multicast

### ISSUE THREAD

**Issue by jordens** [quartiq/stabilizer#786]
* investigate using multicast for streaming
* solves the ARP cache lifetime issue and related potential dropouts
* allows simultaneous reception/logging
* probably no need to join any multicast group as we only send (before #613 )

**Comment by ryan-summers** [comment]
@jordens I took a look, and the main question here is to figure out what broadcast address to use.

Some options:
1. Leave the current IP-configuration as-is, such that the client just requests a broadcast address (requires no firmware changes)
2. Fix the firmware to broadcast to some fixed UDP multicast address that we select and update tools to point at that

It seems like (1) may be more supportive of multiple Stabilizers on the same network. I also suspect this would be relatively trivial to update the test tools to do this.

**Comment by jordens** [comment]
(1) is the way to go.
