### ISSUE TITLE
stream_target in flash crashes due to DHCP not yet complete

### ISSUE THREAD

**Issue by jordens** [quartiq/stabilizer#887]
The local IP isn't set yet but it already tries opening the stream and crashes.

```
WARN - Network link DOWN                                                                                                                                                                             
INFO - Opening stream                                                                             
panicked at /home/rj/.cargo/git/checkouts/smoltcp-nal-f2ec3ae73a86846c/3e3373e/src/lib.rs:569:14:                                                                                                    
called `Option::unwrap()` on a `None` value
```

https://github.com/quartiq/smoltcp-nal/blob/3e3373e/src/lib.rs#L569

**Comment by jordens** [comment]
I think:

* let's make smoltcp-nal not crash here but Err instead
* and then let's make sure that the stream udp socket gets reset/reconnected on DHCP IP change the same way the MQTT stuff gets reset (IIRC that works nicely).

**Comment by ryan-summers** [comment]
> * and then let's make sure that the stream udp socket gets reset/reconnected on DHCP IP change the same way the MQTT stuff gets reset (IIRC that works nicely).

The socket closure on address update is handled at the smoltcp-nal layer:
https://github.com/quartiq/smoltcp-nal/blob/1f7338059538848346051f8b498f897962394b0a/src/lib.rs#L254-L261

We'll need to add logic to Stabilizer to reconnect though, I'll open a PR.
