### ISSUE TITLE
[v1.1 hw] JTAG TDI is shared with SPI3_NSS

### ISSUE THREAD

**Issue by jordens** [quartiq/stabilizer#93]
Add an explanation that JTAG debuggers will conflict on that pin and that SWD debuggers must leave TDI high-z.

**Comment by jordens** [comment]
hardware issue

**Comment by gkasprow** [comment]
added note on schmeatic and PCB
![obraz](https://user-images.githubusercontent.com/4325054/95905836-9ec80c80-0d99-11eb-9fec-8fd008402945.png)
