### ISSUE TITLE
cargo: no such subcommand: `objcopy`

### ISSUE THREAD

**Issue by nkuh** [quartiq/stabilizer#95]
Error:
no such subcommand: `objcopy`
Solution: 
cargo install cargo-binutils

Should it be added to readme?

**Comment by jordens** [comment]
The readme should not duplicate information in e.g. the [embedded book](https://rust-embedded.github.io/book/) or the `cargo-binutils` documentation. Doing so will diverge and lead to outdated information. But linking is fine. @nkuh could you do that?

https://github.com/rust-embedded/cargo-binutils

```
cargo install cargo-binutils
rustup component add llvm-tools-preview
```

**Comment by nkuh** [comment]
@jordens How can I do these changes? Via a new branch, then pull request?

**Comment by jordens** [comment]
Yes. That would be great.
